---
title: "`r Sys.Date()`의 날씨 보고서"
author: "최의용"
output:
  html_document:
    fig_width: 10
    fig_height: 6
    highlight: textmate
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    fig_height: 6
    fig_width: 10
    toc: no
  word_document:
    fig_height: 6
    fig_width: 9
    toc: no  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, echo=FALSE}
library(rvest)
library(reshape2)
library(lubridate)
library(DT)
library(wordcloud)
library(wordcloud2)
library(RColorBrewer)

library(KoNLP)
library(ggplot2)
library(dplyr)
library(stringr)
library(purrr)
```

```{r echo=FALSE}
news_url <- "https://news.naver.com/main/home.nhn"

news_html <- read_html(news_url) 


hdline_urls <- news_html %>% 
  html_nodes(".hdline_article_list") %>%
  html_nodes(".hdline_cluster_more") %>% 
  html_nodes("a") %>% 
  html_attr("href")

hdline_urls <- paste0("https://news.naver.com",hdline_urls)

hdline_new_text_sum <- lapply(hdline_urls[1], function(page) {
  hdline_news_url <- page %>% 
    read_html() %>% 
    html_nodes(xpath = '//*[@id="main_content"]/div[2]') %>% 
    html_nodes("a") %>% 
    html_attr("href") %>% 
    unique() 
  
  news_text <- lapply(hdline_news_url, function(news_page){
    news_page %>% 
      read_html() %>% 
      html_nodes("#articleBodyContents._article_body_contents") %>% 
      html_text()
  }) 
  
  news_text <- news_text %>% 
    unlist() %>% 
    str_replace_all("flash 오류를 우회하기 위한 함수 추가","") %>% 
    str_replace_all("function _flash_removeCallback","") %>% 
    str_replace_all("동영상 뉴스","") %>% 
    str_replace_all("\\W"," ") %>% 
    str_replace_all("   "," ")
}
)
```


```{r}
asdf <- hdline_new_text_sum[[1]]

asdf <- asdf[1]
asdf <- "가나다라마바"
nouns <- KoNLP::extractNoun(asdf)


# table 형태로 변환
wordcount <- table(unlist(nouns))

df.word  <- as.data.frame(wordcount, stringsAsFactors = FALSE)
df.word <- rename(df.word, word = Var1, freq = Freq)

word.freq  <- df.word %>% 
  filter(nchar(word) >=2 & freq >= 2) %>% 
  arrange(desc(freq)) 



wordcloud::wordcloud(words = word.freq$word, freq = word.freq$freq,
                     min.freq = 2, max.words = 200,
                     random.order = FALSE, rot.per = 0.1,
                     scale= c(5,0.5),
                     colors = brewer.pal(8, "Dark2"))
```



```{r echo=FALSE}
weather_url <- "https://weather.naver.com/rgn/cityWetrMain.nhn"

weather_html <- read_html(weather_url) 

weather_table <- weather_html %>% 
  html_nodes(".tbl_weather.tbl_today") %>% 
  html_table() %>% 
  as.data.frame()

weather_table <- apply(weather_table, 2, function(x) gsub("\t","",x))
weather_table <- apply(weather_table, 2, function(x) gsub("기온","",x))
weather_table <- apply(weather_table, 2, function(x) gsub("강수확률","",x))
weather_table <- apply(weather_table, 2, function(x) gsub("℃","",x))
weather_table <- apply(weather_table, 2, function(x) gsub("%","",x))

mor_noon <- c("오전","오후")
colnames_set <- c("기후", "기온(℃)", "강수확률(%)")

morning <- colsplit(weather_table[,2], "\r\n",paste0(mor_noon[1],colnames_set))
afternoon <- colsplit(weather_table[,3], "\r\n",paste0(mor_noon[2],colnames_set))

weather_table <- cbind("지역" = weather_table[,1],morning,afternoon)
```

## 지역별 날씨

### `r weather_table[1,1]`

### `r weather_table[2,1]`

### `r weather_table[3,1]`

### `r weather_table[4,1]`

### `r weather_table[5,1]`

### `r weather_table[6,1]`

### `r weather_table[7,1]`

### `r weather_table[8,1]`

### `r weather_table[9,1]`

### `r weather_table[10,1]`

### `r weather_table[11,1]`

### `r weather_table[12,1]`




```{r echo=FALSE}
datatable(weather_table)
```

